// frontend/app/pages/admin/dashboard.vue
<template>
    <div class="flex-1 flex flex-col overflow-hidden bg-slate-50/50 dark:bg-slate-950/50">
        <header
            class="h-16 border-b bg-card/50 backdrop-blur-md px-6 flex items-center justify-between sticky top-0 z-10">
            <div>
                <h1 class="text-xl font-bold tracking-tight text-slate-900 dark:text-slate-100">Dashboard</h1>
                <p class="text-xs text-muted-foreground">Historical trends and storage distribution</p>
            </div>
            <div class="flex items-center gap-2">
                <Button variant="outline" size="sm" @click="fetchAllData" :disabled="loading" class="h-9">
                    <RefreshCw class="w-3.5 h-3.5 mr-2" :class="{ 'animate-spin': loading }" />
                    Sync Data
                </Button>
            </div>
        </header>

        <main class="flex-1 overflow-auto p-6 space-y-6">
            <!-- TOP STATS -->
            <div class="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
                <Card v-for="stat in topStats" :key="stat.label"
                    class="border-slate-200 dark:border-slate-800 shadow-xs group hover:border-primary/50 transition-colors">
                    <CardHeader class="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle class="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">{{
                            stat.label }}</CardTitle>
                        <component :is="stat.icon"
                            class="h-4 w-4 text-primary opacity-70 group-hover:scale-110 transition-transform" />
                    </CardHeader>
                    <CardContent>
                        <div class="text-2xl font-bold">{{ stat.value }}</div>
                        <p class="text-[10px] text-muted-foreground mt-1">{{ stat.sub }}</p>
                    </CardContent>
                </Card>
            </div>

            <div class="grid gap-6 md:grid-cols-2 lg:grid-cols-3 lg:h-[450px]">
                <!-- STORAGE DISTRIBUTION -->
                <Card class="border-slate-200 dark:border-slate-800 flex flex-col shadow-sm">
                    <CardHeader>
                        <CardTitle class="text-sm font-bold flex items-center gap-2">
                            <Pizza class="w-4 h-4 text-primary" />
                            Storage Distribution (by Bucket)
                        </CardTitle>
                    </CardHeader>
                    <CardContent class="flex-1 flex items-center justify-center p-6 pt-0 min-h-0">
                        <Doughnut v-if="distributionData" :data="distributionData" :options="doughnutOptions" />
                        <div v-else class="flex flex-col items-center opacity-20 animate-pulse">
                            <PieChart class="w-12 h-12" />
                            <span class="text-xs italic">Gathering distribution data...</span>
                        </div>
                    </CardContent>
                </Card>

                <!-- CONTENT-TYPE BREAKDOWN -->
                <Card class="border-slate-200 dark:border-slate-800 flex flex-col shadow-sm">
                    <CardHeader>
                        <CardTitle class="text-sm font-bold flex items-center gap-2">
                            <PieChart class="w-4 h-4 text-primary" />
                            Content-Type Breakdown (by Size)
                        </CardTitle>
                    </CardHeader>
                    <CardContent class="flex-1 flex items-center justify-center p-6 pt-0 min-h-0">
                        <Doughnut v-if="contentTypeData" :data="contentTypeData" :options="contentTypeOptions" />
                        <div v-else class="flex flex-col items-center opacity-20 animate-pulse">
                            <PieChart class="w-12 h-12" />
                            <span class="text-xs italic">Gathering breakdown data...</span>
                        </div>
                    </CardContent>
                </Card>

                <!-- REQUEST TRENDS -->
                <Card class="border-slate-200 dark:border-slate-800 flex flex-col shadow-sm">
                    <CardHeader>
                        <CardTitle class="text-sm font-bold flex items-center gap-2">
                            <TrendingUp class="w-4 h-4 text-primary" />
                            Request Trends (Last 30 Days)
                        </CardTitle>
                    </CardHeader>
                    <CardContent class="flex-1 p-6 pt-0 min-h-0">
                        <Line v-if="trendsData" :data="trendsData" :options="lineOptions" />
                        <div v-else class="flex h-full items-center justify-center opacity-20">
                            <Activity class="w-12 h-12" />
                        </div>
                    </CardContent>
                </Card>
            </div>

            <!-- BUCKET GROWTH -->
            <Card class="border-slate-200 dark:border-slate-800 shadow-sm h-[400px]">
                <CardHeader>
                    <CardTitle class="text-sm font-bold flex items-center gap-2">
                        <LineChart class="w-4 h-4 text-primary" />
                        Historical Growth (Capacity Trajectory)
                    </CardTitle>
                </CardHeader>
                <CardContent class="h-full pb-12 p-6 pt-0">
                    <Line v-if="growthData" :data="growthData" :options="growthOptions" />
                    <div v-else class="flex h-full items-center justify-center opacity-20">
                        <Database class="w-12 h-12" />
                    </div>
                </CardContent>
            </Card>

            <!-- LIVE AUDIT TRAIL LOGS -->
            <Card class="border-slate-200 dark:border-slate-800 shadow-sm flex flex-col h-[400px] overflow-hidden">
                <CardHeader class="flex flex-row items-center justify-between pb-3 border-b">
                    <CardTitle class="text-sm font-bold flex items-center gap-2">
                        <Activity class="w-4 h-4 text-primary" />
                        Live Audit Trail & S3 Events
                    </CardTitle>
                    <div class="flex items-center gap-4">
                        <!-- Connection Status -->
                        <div class="flex items-center gap-1.5 text-xs font-semibold select-none">
                            <span class="relative flex h-2 w-2">
                                <span :class="[
                                    'absolute inline-flex h-full w-full rounded-full opacity-75',
                                    wsStatus === 'connected' ? 'animate-ping bg-emerald-400' : '',
                                    wsStatus === 'connecting' ? 'animate-ping bg-amber-400' : '',
                                    wsStatus === 'disconnected' ? 'bg-rose-400' : ''
                                ]"></span>
                                <span :class="[
                                    'relative inline-flex rounded-full h-2 w-2',
                                    wsStatus === 'connected' ? 'bg-emerald-500' : '',
                                    wsStatus === 'connecting' ? 'bg-amber-500' : '',
                                    wsStatus === 'disconnected' ? 'bg-rose-500' : ''
                                ]"></span>
                            </span>
                            <span :class="[
                                'text-[10px] uppercase tracking-wider font-bold',
                                wsStatus === 'connected' ? 'text-emerald-500' : '',
                                wsStatus === 'connecting' ? 'text-amber-500' : '',
                                wsStatus === 'disconnected' ? 'text-rose-500' : ''
                            ]">{{ wsStatus }}</span>
                        </div>
                        <Button variant="ghost" size="xs" @click="auditLogs = []" class="h-7 text-[10px] uppercase font-bold tracking-wider">
                            Clear Feed
                        </Button>
                    </div>
                </CardHeader>
                <CardContent class="flex-1 bg-slate-950 p-4 font-mono text-[11px] leading-5 text-slate-300 overflow-y-auto custom-scrollbar select-text">
                    <div v-if="auditLogs.length === 0" class="flex flex-col items-center justify-center h-full text-slate-500 select-none">
                        <Activity class="w-8 h-8 opacity-20 mb-2 animate-pulse" />
                        <span class="italic">Waiting for S3 events...</span>
                    </div>
                    <div v-else class="space-y-1">
                        <div v-for="(log, idx) in auditLogs" :key="idx" class="flex items-start gap-3 hover:bg-white/5 py-0.5 px-1 rounded transition-colors animate-in fade-in duration-300">
                            <span class="text-slate-600 select-none shrink-0">{{ new Date(log.timestamp).toLocaleTimeString() }}</span>
                            <span :class="[
                                'px-1.5 py-0.5 rounded text-[9px] font-bold uppercase tracking-wider shrink-0',
                                log.result === 'success' ? 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20' : 'bg-rose-500/10 text-rose-400 border border-rose-500/20'
                            ]">{{ log.action.split(':').pop() }}</span>
                            <span class="text-slate-400 truncate flex-1" :title="log.resource">{{ log.resource }}</span>
                            <span class="text-slate-500 shrink-0">{{ log.user || 'anonymous' }}</span>
                            <span class="text-slate-600 shrink-0 font-bold tracking-tighter">{{ log.ip }}</span>
                        </div>
                    </div>
                </CardContent>
            </Card>

            <!-- BUCKET QUOTAS & CAPACITY ALERTS -->
            <Card class="border-slate-200 dark:border-slate-800 shadow-sm">
                <CardHeader>
                    <CardTitle class="text-sm font-bold flex items-center gap-2">
                        <ShieldAlert class="w-4 h-4 text-primary" />
                        Bucket Quotas & Capacity Warnings
                    </CardTitle>
                </CardHeader>
                <CardContent class="p-6 pt-0">
                    <div v-if="!bucketsInfo || bucketsInfo.length === 0" class="text-center py-6 text-xs text-muted-foreground">
                        No buckets configured.
                    </div>
                    <div v-else class="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
                        <div v-for="b in bucketsInfo" :key="b.Name" 
                            class="p-4 rounded-xl border bg-card hover:border-primary/30 transition-all flex flex-col justify-between gap-3">
                            <div class="flex items-center justify-between">
                                <div class="flex items-center gap-2">
                                    <div class="h-8 w-8 rounded-lg bg-indigo-500/10 text-indigo-500 flex items-center justify-center">
                                        <Database class="w-4 h-4" />
                                    </div>
                                    <span class="font-bold text-sm text-slate-800 dark:text-slate-200 font-mono">{{ b.Name }}</span>
                                </div>
                                <Badge v-if="b.QuotaBytes > 0 && (b.CurrentSize / b.QuotaBytes) >= 0.9" variant="destructive" class="text-[9px] uppercase font-bold animate-pulse">
                                    Critical
                                </Badge>
                                <Badge v-else-if="b.QuotaBytes > 0 && (b.CurrentSize / b.QuotaBytes) >= 0.75" variant="warning" class="text-[9px] uppercase font-bold">
                                    Warning
                                </Badge>
                                <Badge v-else variant="outline" class="text-[9px] uppercase font-semibold text-emerald-500 border-emerald-500/20 bg-emerald-500/5">
                                    Healthy
                                </Badge>
                            </div>
                            
                            <div class="space-y-1">
                                <div class="flex justify-between text-[10px] text-muted-foreground">
                                    <span>Usage: {{ formatSize(b.CurrentSize) }}</span>
                                    <span>Quota: {{ b.QuotaBytes > 0 ? formatSize(b.QuotaBytes) : 'Unlimited' }}</span>
                                </div>
                                <div class="h-2 w-full bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden">
                                    <div class="h-full rounded-full transition-all duration-300"
                                        :class="getQuotaProgressColor(b.CurrentSize, b.QuotaBytes)"
                                        :style="{ width: getQuotaPercent(b.CurrentSize, b.QuotaBytes) + '%' }">
                                    </div>
                                </div>
                                <div class="flex justify-between items-center text-[9px] mt-1">
                                    <span class="text-muted-foreground">{{ getQuotaPercent(b.CurrentSize, b.QuotaBytes) }}% utilized</span>
                                    <span v-if="b.QuotaBytes > 0 && b.CurrentSize >= b.QuotaBytes" class="text-rose-500 font-bold">Quota exceeded!</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </CardContent>
            </Card>
        </main>
    </div>
</template>

<script setup>
import { ref, onMounted, onUnmounted, computed } from 'vue'

useSeoMeta({
    title: 'Analytics Dashboard | GravSpace',
    description: 'Monitor real-time storage metrics, historical trends, and data distribution across your buckets.',
})
import {
    RefreshCw, TrendingUp, Database, Activity, User, Pizza,
    PieChart, LineChart, FileUp, Download, Trash2, ShieldAlert
} from 'lucide-vue-next'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { useAuth } from '@/composables/useAuth'

// Chart.js registration
import {
    Chart as ChartJS,
    Title,
    Tooltip,
    Legend,
    ArcElement,
    LineElement,
    PointElement,
    LinearScale,
    CategoryScale,
    Filler
} from 'chart.js'
import { Doughnut, Line } from 'vue-chartjs'

ChartJS.register(
    Title, Tooltip, Legend, ArcElement, LineElement,
    PointElement, LinearScale, CategoryScale, Filler
)

const { authState, authFetch } = useAuth()
const config = useRuntimeConfig()
const API_BASE = config.public.apiBase

const loading = ref(false)
const stats = ref({})
const rawStorageHistory = ref([])
const rawRequestTrends = ref({})
const rawContentTypeBreakdown = ref([])
const bucketsInfo = ref([])

function formatSavings(logical, physical) {
    if (!logical || logical <= 0) return '0 B (0%)'
    const diff = logical - physical
    if (diff <= 0) return '0 B (0%)'
    const percent = Math.min(100, Math.round((diff / logical) * 100))
    return `${formatSize(diff)} (${percent}%)`
}

function getQuotaPercent(current, quota) {
    if (!quota || quota <= 0) return 0
    return Math.min(100, Math.round((current / quota) * 100))
}

function getQuotaProgressColor(current, quota) {
    if (!quota || quota <= 0) return 'bg-emerald-500'
    const pct = current / quota
    if (pct >= 0.9) return 'bg-rose-500'
    if (pct >= 0.75) return 'bg-amber-500'
    return 'bg-emerald-500'
}

const topStats = computed(() => [
    { label: 'Total Objects', value: stats.value.total_objects || 0, icon: Database, sub: stats.value.deduplicated_count ? `${stats.value.deduplicated_count} deduplicated` : 'No duplicates' },
    { label: 'Logical Capacity', value: formatSize(stats.value.total_size || 0), icon: Activity, sub: 'Virtual S3 size' },
    { label: 'Physical Disk Space', value: formatSize(stats.value.physical_size || 0), icon: Database, sub: 'Actual space used' },
    { label: 'Storage Saved', value: formatSavings(stats.value.total_size, stats.value.physical_size), icon: FileUp, sub: 'Deduplication + Gzip' }
])

const distributionData = computed(() => {
    if (!rawStorageHistory.value || rawStorageHistory.value.length === 0) return null

    // Use the latest snapshot per bucket
    const buckets = {}
    rawStorageHistory.value.forEach(s => {
        buckets[s.Bucket] = s.Size
    })

    const labels = Object.keys(buckets)
    if (labels.length === 0) return null

    return {
        labels,
        datasets: [{
            data: Object.values(buckets),
            backgroundColor: [
                '#6366f1', '#a855f7', '#ec4899', '#f43f5e',
                '#f59e0b', '#10b981', '#06b6d4', '#3b82f6'
            ],
            borderWidth: 0,
            hoverOffset: 15
        }]
    }
})

const contentTypeData = computed(() => {
    if (!rawContentTypeBreakdown.value || rawContentTypeBreakdown.value.length === 0) return null

    const labels = rawContentTypeBreakdown.value.map(item => item.category)
    const sizes = rawContentTypeBreakdown.value.map(item => item.totalSize)
    if (labels.length === 0) return null

    return {
        labels,
        datasets: [{
            data: sizes,
            backgroundColor: [
                '#3b82f6', // blue (Images)
                '#10b981', // emerald (Videos)
                '#f59e0b', // amber (Audio)
                '#6366f1', // indigo (Documents)
                '#8b5cf6', // violet (Code & Config)
                '#ec4899', // pink (Archives)
                '#64748b'  // slate (Other)
            ],
            borderWidth: 0,
            hoverOffset: 15
        }]
    }
})

const contentTypeOptions = computed(() => ({
    responsive: true,
    maintainAspectRatio: false,
    cutout: '75%',
    plugins: {
        legend: { position: 'bottom', labels: { boxWidth: 10, padding: 15, font: { size: 10 } } },
        tooltip: {
            callbacks: {
                label: (context) => {
                    const value = context.raw
                    return ` ${context.label}: ${formatSize(value)}`
                }
            }
        }
    }
}))

const trendsData = computed(() => {
    if (!rawRequestTrends.value || Object.keys(rawRequestTrends.value).length === 0) return null

    // Get union of all days
    const days = new Set()
    Object.values(rawRequestTrends.value).forEach(actionDays => {
        actionDays.forEach(d => days.add(d.day))
    })
    const sortedDays = Array.from(days).sort()

    const datasets = []
    const actionConfig = {
        's3:PutObject': { label: 'Uploads', color: '#10b981' },
        's3:DeleteObject': { label: 'Deletions', color: '#ef4444' },
        's3:GetObject': { label: 'Downloads', color: '#3b82f6' }
    }

    Object.entries(rawRequestTrends.value).forEach(([action, data]) => {
        if (!actionConfig[action]) return

        const counts = sortedDays.map(day => {
            const match = data.find(d => d.day === day)
            return match ? match.count : 0
        })

        datasets.push({
            label: actionConfig[action].label,
            data: counts,
            borderColor: actionConfig[action].color,
            backgroundColor: actionConfig[action].color + '20',
            fill: true,
            tension: 0.4,
            pointRadius: 2,
            pointHoverRadius: 6
        })
    })

    return { datasets, labels: sortedDays.map(d => d.split('-').slice(1).join('/')) }
})

const growthData = computed(() => {
    if (!rawStorageHistory.value || rawStorageHistory.value.length === 0) return null

    // Get all unique dates from snapshots and sort them
    const allDates = Array.from(new Set(rawStorageHistory.value.map(s => {
        // Handle both ISO strings and SQLite dates
        const date = s.Timestamp.includes('T') ? s.Timestamp.split('T')[0] : s.Timestamp.split(' ')[0]
        return date
    }))).sort()

    const buckets = Array.from(new Set(rawStorageHistory.value.map(s => s.Bucket)))

    const datasets = buckets.map((bucket, i) => {
        const data = allDates.map(day => {
            const match = rawStorageHistory.value.find(s => s.Bucket === bucket && s.Timestamp.startsWith(day))
            return match ? match.Size : 0
        })

        const colors = ['#6366f1', '#a855f7', '#ec4899', '#f43f5e', '#f59e0b', '#10b981', '#06b6d4', '#3b82f6']

        return {
            label: bucket,
            data: data,
            borderColor: colors[i % colors.length],
            backgroundColor: colors[i % colors.length] + '10',
            borderWidth: 2,
            tension: 0.3,
            pointRadius: 3,
            fill: true
        }
    })

    return { datasets, labels: allDates.map(d => d.split('-').slice(1).join('/')) }
})

const doughnutOptions = {
    responsive: true,
    maintainAspectRatio: false,
    cutout: '75%',
    plugins: {
        legend: { position: 'bottom', labels: { boxWidth: 10, padding: 15, font: { size: 10 } } }
    }
}

const lineOptions = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
        legend: { display: false }
    },
    scales: {
        x: { grid: { display: false }, ticks: { font: { size: 9 } } },
        y: {
            beginAtZero: true,
            grid: { color: 'rgba(0,0,0,0.05)' },
            ticks: { stepSize: 1, font: { size: 9 } }
        }
    }
}

const growthOptions = {
    ...lineOptions,
    plugins: {
        legend: { position: 'top', labels: { boxWidth: 10, font: { size: 10 } } }
    },
    scales: {
        x: { grid: { display: false }, ticks: { font: { size: 9 } } },
        y: {
            grid: { color: 'rgba(0,0,0,0.05)' },
            ticks: {
                callback: (val) => formatSize(val),
                font: { size: 9 }
            }
        }
    }
}

async function fetchAllData() {
    loading.value = true
    try {
        const [statsRes, storageRes, trendsRes, bucketsRes, contentTypeRes] = await Promise.all([
            authFetch(`${API_BASE}/admin/stats`),
            authFetch(`${API_BASE}/admin/analytics/storage?days=30`),
            authFetch(`${API_BASE}/admin/analytics/requests?days=30`),
            authFetch(`${API_BASE}/admin/buckets`),
            authFetch(`${API_BASE}/admin/analytics/content-types`)
        ])

        if (contentTypeRes && contentTypeRes.ok) {
            rawContentTypeBreakdown.value = (await contentTypeRes.json()) || []
        }

        if (statsRes.ok) stats.value = (await statsRes.json()) || {}
        if (storageRes.ok) rawStorageHistory.value = (await storageRes.json()) || []
        if (trendsRes.ok) rawRequestTrends.value = (await trendsRes.json()) || {}
        
        if (bucketsRes.ok) {
            const bucketNames = (await bucketsRes.json()) || []
            const details = await Promise.all(bucketNames.map(async name => {
                try {
                    const infoRes = await authFetch(`${API_BASE}/admin/buckets/${name}/info`)
                    if (infoRes.ok) return await infoRes.json()
                } catch (err) {
                    console.error(`Failed to fetch bucket info for ${name}`, err)
                }
                return null
            }))
            bucketsInfo.value = details.filter(Boolean)
        }
    } catch (e) {
        console.error('Failed to sync analytics', e)
    } finally {
        loading.value = false
    }
}

function formatSize(bytes) {
    if (bytes === 0) return '0 B'
    const k = 1024
    const sizes = ['B', 'KB', 'MB', 'GB', 'TB']
    const i = Math.floor(Math.log(bytes) / Math.log(k))
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i]
}

const wsStatus = ref('disconnected')
const auditLogs = ref([])
let wsConn = null

function connectWS() {
    if (wsConn) {
        try {
            wsConn.close()
        } catch(e){}
    }

    wsStatus.value = 'connecting'
    const protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:'
    const token = authState.value?.token || ''

    let wsUrl = ''
    if (API_BASE.startsWith('http://') || API_BASE.startsWith('https://')) {
        const host = API_BASE.replace(/^https?:\/\//, '').replace(/\/$/, '')
        wsUrl = `${protocol}//${host}/admin/audit/stream`
    } else {
        // API_BASE is relative (e.g. /api or /)
        if (window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1') {
            // Local dev environment: connect directly to Go backend on port 8080
            wsUrl = `${protocol}//localhost:8080/admin/audit/stream`
        } else {
            // Production: connect relative to current host
            const cleanApiBase = API_BASE.startsWith('/') ? API_BASE : '/' + API_BASE
            const host = window.location.host + cleanApiBase.replace(/\/$/, '')
            wsUrl = `${protocol}//${host}/admin/audit/stream`
        }
    }

    wsConn = new WebSocket(`${wsUrl}?token=${encodeURIComponent(token)}`)

    wsConn.onopen = () => {
        wsStatus.value = 'connected'
    }

    wsConn.onmessage = (event) => {
        try {
            const logEntry = JSON.parse(event.data)
            auditLogs.value.push(logEntry)
            if (auditLogs.value.length > 50) {
                auditLogs.value.shift()
            }
        } catch (e) {
            console.error('Failed to parse audit event:', e)
        }
    }

    wsConn.onclose = () => {
        wsStatus.value = 'disconnected'
        setTimeout(() => {
            if (wsConn && wsConn.readyState === WebSocket.CLOSED) {
                connectWS()
            }
        }, 3000)
    }

    wsConn.onerror = () => {
        wsStatus.value = 'disconnected'
    }
}

onMounted(() => {
    fetchAllData()
    connectWS()
})

onUnmounted(() => {
    if (wsConn) {
        wsConn.close()
    }
})
</script>

// frontend/src/routes/admin/dashboard.tsx
import { createFileRoute } from '@tanstack/react-router'
import { useState, useEffect, useRef, useCallback } from 'react'
import {
  Database,
  Activity,
  FileUp,
  RefreshCw,
  PieChart,
  BarChart3,
} from 'lucide-react'
import {
  AreaChart,
  Area,
  BarChart,
  Bar,
  PieChart as RPieChart,
  Pie,
  Cell,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
} from 'recharts'
import { Button } from '../../components/ui/button'
import { Badge } from '../../components/ui/badge'
import { useAuth } from '../../hooks/useAuth'

export const Route = createFileRoute('/admin/dashboard')({
  component: DashboardPage,
  head: () => ({ meta: [{ title: 'Dashboard | GravSpace' }] }),
})

const API_BASE = import.meta.env.VITE_API_BASE ?? '/api'
const CHART_COLORS = ['#6366f1', '#a855f7', '#ec4899', '#f43f5e', '#f59e0b', '#10b981', '#06b6d4', '#3b82f6']
const TYPE_COLORS = ['#3b82f6', '#10b981', '#f59e0b', '#6366f1', '#8b5cf6', '#ec4899', '#64748b']

function formatSize(bytes: number): string {
  if (!bytes || bytes === 0) return '0 B'
  const k = 1024
  const sizes = ['B', 'KB', 'MB', 'GB', 'TB']
  const i = Math.floor(Math.log(bytes) / Math.log(k))
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i]
}

function formatSavings(logical: number, physical: number): string {
  if (!logical || logical <= 0) return '0 B (0%)'
  const diff = logical - physical
  if (diff <= 0) return '0 B (0%)'
  const percent = Math.min(100, Math.round((diff / logical) * 100))
  return `${formatSize(diff)} (${percent}%)`
}

type WsStatus = 'connected' | 'connecting' | 'disconnected'

function DashboardPage() {
  const { authFetch, authState } = useAuth()
  const [loading, setLoading] = useState(false)
  const [stats, setStats] = useState<Record<string, any>>({})
  const [storageHistory, setStorageHistory] = useState<any[]>([])
  const [requestTrends, setRequestTrends] = useState<Record<string, any[]>>({})
  const [contentTypes, setContentTypes] = useState<any[]>([])
  const [wsStatus, setWsStatus] = useState<WsStatus>('disconnected')
  const [liveLogs, setLiveLogs] = useState<any[]>([])
  const wsRef = useRef<WebSocket | null>(null)

  const fetchAllData = useCallback(async () => {
    setLoading(true)
    try {
      const [statsRes, storageRes, trendsRes, contentTypeRes] = await Promise.all([
        authFetch(`${API_BASE}/admin/stats`),
        authFetch(`${API_BASE}/admin/analytics/storage?days=30`),
        authFetch(`${API_BASE}/admin/analytics/requests?days=30`),
        authFetch(`${API_BASE}/admin/analytics/content-types`),
      ])
      if (statsRes.ok) setStats(await statsRes.json())
      if (storageRes.ok) setStorageHistory(await storageRes.json())
      if (trendsRes.ok) setRequestTrends(await trendsRes.json())
      if (contentTypeRes.ok) setContentTypes(await contentTypeRes.json())
    } catch (e) {
      console.error('Failed to fetch dashboard data', e)
    } finally {
      setLoading(false)
    }
  }, [authFetch])

  const connectWS = useCallback(() => {
    if (wsRef.current) wsRef.current.close()
    setWsStatus('connecting')
    const protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:'
    const token = authState?.token || ''
    let wsUrl = ''
    if (API_BASE.startsWith('http://') || API_BASE.startsWith('https://')) {
      const host = API_BASE.replace(/^https?:\/\//, '').replace(/\/$/, '')
      wsUrl = `${protocol}//${host}/admin/audit/stream`
    } else {
      if (window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1') {
        wsUrl = `${protocol}//localhost:8080/admin/audit/stream`
      } else {
        const cleanBase = API_BASE.startsWith('/') ? API_BASE : `/${API_BASE}`
        wsUrl = `${protocol}//${window.location.host}${cleanBase.replace(/\/$/, '')}/admin/audit/stream`
      }
    }
    const ws = new WebSocket(`${wsUrl}?token=${encodeURIComponent(token)}`)
    wsRef.current = ws
    ws.onopen = () => setWsStatus('connected')
    ws.onmessage = (event) => {
      try {
        const logEntry = JSON.parse(event.data)
        setLiveLogs((prev) => [logEntry, ...prev].slice(0, 50))

        const status = logEntry.Status || logEntry.status || ''
        if (status === 'success' || status === 'allowed') {
          const action = logEntry.Action || logEntry.action || ''
          const details = logEntry.Details || logEntry.details || {}
          const size = details.size || details.Size || 0

          if (action.includes('PutObject')) {
            setStats(prev => ({
              ...prev,
              total_objects: (prev.total_objects || 0) + 1,
              total_size: (prev.total_size || 0) + size,
              physical_size: (prev.physical_size || 0) + size,
            }))
          } else if (action.includes('DeleteObject')) {
            setStats(prev => ({
              ...prev,
              total_objects: Math.max(0, (prev.total_objects || 0) - 1),
              total_size: Math.max(0, (prev.total_size || 0) - size),
              physical_size: Math.max(0, (prev.physical_size || 0) - size),
            }))
          }
        }
      } catch (e) {
        console.error('Failed to parse WS log entry', e)
      }
    }
    ws.onclose = () => {
      setWsStatus('disconnected')
      setTimeout(() => {
        if (wsRef.current?.readyState === WebSocket.CLOSED) connectWS()
      }, 3000)
    }
    ws.onerror = () => setWsStatus('disconnected')
  }, [authState?.token])

  useEffect(() => {
    fetchAllData()
    connectWS()
    return () => wsRef.current?.close()
  }, [])

  // Build chart data
  const storageByBucket = (() => {
    const map: Record<string, number> = {}
    storageHistory.forEach((s) => { map[s.Bucket] = s.Size })
    return Object.entries(map).map(([name, value], i) => ({ name, value, fill: CHART_COLORS[i % CHART_COLORS.length] }))
  })()

  const contentTypePie = contentTypes.map((ct, i) => ({
    name: ct.category,
    value: ct.totalSize,
    fill: TYPE_COLORS[i % TYPE_COLORS.length],
  }))

  // Build trends area chart data
  const trendsChartData = (() => {
    const days = new Set<string>()
    Object.values(requestTrends).forEach((arr) => arr.forEach((d) => days.add(d.day)))
    const sorted = Array.from(days).sort()
    return sorted.map((day) => {
      const row: Record<string, any> = { day: day.split('-').slice(1).join('/') }
      const get3PO = (requestTrends['s3:PutObject'] || []).find((d) => d.day === day)
      const getDO = (requestTrends['s3:DeleteObject'] || []).find((d) => d.day === day)
      const getGO = (requestTrends['s3:GetObject'] || []).find((d) => d.day === day)
      row.Uploads = get3PO?.count || 0
      row.Deletions = getDO?.count || 0
      row.Downloads = getGO?.count || 0
      return row
    })
  })()

  const topStats = [
    {
      label: 'Total Objects',
      value: stats.total_objects || 0,
      icon: Database,
      sub: stats.deduplicated_count ? `${stats.deduplicated_count} deduplicated` : 'No duplicates',
      accent: 'indigo',
    },
    {
      label: 'Logical Capacity',
      value: formatSize(stats.total_size || 0),
      icon: Activity,
      sub: 'Virtual S3 size',
      accent: 'sky',
    },
    {
      label: 'Physical Disk Space',
      value: formatSize(stats.physical_size || 0),
      icon: Database,
      sub: 'Actual space used',
      accent: 'violet',
    },
    {
      label: 'Storage Saved',
      value: formatSavings(stats.total_size, stats.physical_size),
      icon: FileUp,
      sub: 'Deduplication + Gzip',
      accent: 'emerald',
    },
  ]

  const accentMap: Record<string, string> = {
    indigo: 'bg-indigo-500',
    sky: 'bg-sky-500',
    violet: 'bg-violet-500',
    emerald: 'bg-emerald-500',
  }
  const iconBgMap: Record<string, string> = {
    indigo: 'bg-indigo-500/10 text-indigo-500',
    sky: 'bg-sky-500/10 text-sky-500',
    violet: 'bg-violet-500/10 text-violet-500',
    emerald: 'bg-emerald-500/10 text-emerald-500',
  }

  return (
    <div className="flex-1 flex flex-col overflow-hidden bg-slate-50/50 dark:bg-slate-950/50">
      {/* Header */}
      <header className="h-16 border-b bg-card/50 backdrop-blur-md px-6 flex items-center justify-between sticky top-0 z-10">
        <div>
          <h1 className="text-lg font-semibold tracking-tight">Dashboard</h1>
          <p className="text-xs text-muted-foreground">Historical trends and storage distribution</p>
        </div>
        <div className="flex items-center gap-3">
          {/* WS Status */}
          <div className="flex items-center gap-1.5 select-none">
            <span className="relative flex h-2 w-2">
              <span
                className={`absolute inline-flex h-full w-full rounded-full opacity-75 ${
                  wsStatus === 'connected'
                    ? 'animate-ping bg-emerald-400'
                    : wsStatus === 'connecting'
                      ? 'animate-ping bg-amber-400'
                      : 'bg-rose-400'
                }`}
              />
              <span
                className={`relative inline-flex rounded-full h-2 w-2 ${
                  wsStatus === 'connected'
                    ? 'bg-emerald-500'
                    : wsStatus === 'connecting'
                      ? 'bg-amber-500'
                      : 'bg-rose-500'
                }`}
              />
            </span>
            <span
              className={`text-[9px] uppercase tracking-widest font-bold ${
                wsStatus === 'connected'
                  ? 'text-emerald-500'
                  : wsStatus === 'connecting'
                    ? 'text-amber-500'
                    : 'text-rose-500'
              }`}
            >
              {wsStatus}
            </span>
          </div>
          <Button
            variant="outline"
            size="sm"
            onClick={fetchAllData}
            disabled={loading}
            className="h-8 border-slate-200 dark:border-slate-800"
          >
            <RefreshCw className={`w-3.5 h-3.5 mr-2 ${loading ? 'animate-spin' : ''}`} />
            Sync
          </Button>
        </div>
      </header>

      <main className="flex-1 overflow-auto p-5 space-y-4">
        {/* TOP STATS */}
        <div className="grid gap-3 grid-cols-2 lg:grid-cols-4">
          {topStats.map((stat, i) => (
            <div
              key={stat.label}
              className="group relative overflow-hidden rounded-xl border border-slate-200 dark:border-slate-800 bg-card p-4 shadow-xs hover:shadow-md hover:border-primary/30 transition-all duration-300"
            >
              <div className={`absolute top-0 left-0 right-0 h-0.5 ${accentMap[stat.accent]}`} />
              <div className="flex items-center justify-between mb-2">
                <span className="text-[9px] font-bold uppercase tracking-widest text-muted-foreground">
                  {stat.label}
                </span>
                <div className={`h-7 w-7 rounded-lg flex items-center justify-center ${iconBgMap[stat.accent]}`}>
                  <stat.icon className="h-3.5 w-3.5 group-hover:scale-110 transition-transform" />
                </div>
              </div>
              <div className="text-xl font-bold tracking-tight">{stat.value}</div>
              <p className="text-[10px] text-muted-foreground mt-0.5 opacity-60">{stat.sub}</p>
            </div>
          ))}
        </div>

        {/* CHARTS 2-COLUMN */}
        <div className="grid gap-4 lg:grid-cols-2">
          {/* Left: Pie Charts */}
          <div className="grid gap-3 grid-cols-2">
            {/* Storage by Bucket */}
            <div className="rounded-xl border border-slate-200 dark:border-slate-800 bg-card shadow-xs overflow-hidden flex flex-col">
              <div className="px-4 pt-3 pb-1.5">
                <div className="flex items-center gap-1.5">
                  <PieChart className="w-3.5 h-3.5 text-primary" />
                  <span className="text-xs font-bold tracking-tight">By Bucket</span>
                </div>
              </div>
              <div className="flex-1 min-h-[180px] px-2 pb-3">
                {storageByBucket.length > 0 ? (
                  <ResponsiveContainer width="100%" height={160}>
                    <RPieChart>
                      <Pie
                        data={storageByBucket}
                        cx="50%"
                        cy="50%"
                        innerRadius={50}
                        outerRadius={70}
                        paddingAngle={2}
                        dataKey="value"
                      >
                        {storageByBucket.map((entry, i) => (
                          <Cell key={i} fill={entry.fill} />
                        ))}
                      </Pie>
                      <Tooltip formatter={(v: any) => formatSize(v)} />
                      <Legend iconSize={8} wrapperStyle={{ fontSize: 9 }} />
                    </RPieChart>
                  </ResponsiveContainer>
                ) : (
                  <div className="flex flex-col items-center justify-center h-full opacity-20 animate-pulse">
                    <PieChart className="w-10 h-10" />
                    <span className="text-[9px] italic mt-1">Loading...</span>
                  </div>
                )}
              </div>
            </div>

            {/* Content Type */}
            <div className="rounded-xl border border-slate-200 dark:border-slate-800 bg-card shadow-xs overflow-hidden flex flex-col">
              <div className="px-4 pt-3 pb-1.5">
                <div className="flex items-center gap-1.5">
                  <BarChart3 className="w-3.5 h-3.5 text-primary" />
                  <span className="text-xs font-bold tracking-tight">By Type</span>
                </div>
              </div>
              <div className="flex-1 min-h-[180px] px-2 pb-3">
                {contentTypePie.length > 0 ? (
                  <ResponsiveContainer width="100%" height={160}>
                    <RPieChart>
                      <Pie
                        data={contentTypePie}
                        cx="50%"
                        cy="50%"
                        innerRadius={50}
                        outerRadius={70}
                        paddingAngle={2}
                        dataKey="value"
                      >
                        {contentTypePie.map((entry, i) => (
                          <Cell key={i} fill={entry.fill} />
                        ))}
                      </Pie>
                      <Tooltip formatter={(v: any) => formatSize(v)} />
                      <Legend iconSize={8} wrapperStyle={{ fontSize: 9 }} />
                    </RPieChart>
                  </ResponsiveContainer>
                ) : (
                  <div className="flex flex-col items-center justify-center h-full opacity-20 animate-pulse">
                    <BarChart3 className="w-10 h-10" />
                    <span className="text-[9px] italic mt-1">Loading...</span>
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* Right: Request Trends Line */}
          <div className="rounded-xl border border-slate-200 dark:border-slate-800 bg-card shadow-xs overflow-hidden flex flex-col">
            <div className="px-4 pt-3 pb-1.5">
              <div className="flex items-center gap-1.5">
                <Activity className="w-3.5 h-3.5 text-primary" />
                <span className="text-xs font-bold tracking-tight">Request Trends (30d)</span>
              </div>
            </div>
            <div className="flex-1 min-h-[200px] px-3 pb-4">
              {trendsChartData.length > 0 ? (
                <ResponsiveContainer width="100%" height={200}>
                  <AreaChart data={trendsChartData} margin={{ top: 5, right: 10, bottom: 0, left: 0 }}>
                    <defs>
                      <linearGradient id="uploads" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor="#10b981" stopOpacity={0.15} />
                        <stop offset="95%" stopColor="#10b981" stopOpacity={0} />
                      </linearGradient>
                      <linearGradient id="downloads" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor="#3b82f6" stopOpacity={0.15} />
                        <stop offset="95%" stopColor="#3b82f6" stopOpacity={0} />
                      </linearGradient>
                      <linearGradient id="deletions" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor="#ef4444" stopOpacity={0.15} />
                        <stop offset="95%" stopColor="#ef4444" stopOpacity={0} />
                      </linearGradient>
                    </defs>
                    <CartesianGrid strokeDasharray="3 3" stroke="rgba(0,0,0,0.04)" />
                    <XAxis dataKey="day" tick={{ fontSize: 8 }} tickCount={10} />
                    <YAxis tick={{ fontSize: 8 }} />
                    <Tooltip />
                    <Legend iconSize={8} wrapperStyle={{ fontSize: 9 }} />
                    <Area type="monotone" dataKey="Uploads" stroke="#10b981" fill="url(#uploads)" strokeWidth={1.5} dot={false} />
                    <Area type="monotone" dataKey="Downloads" stroke="#3b82f6" fill="url(#downloads)" strokeWidth={1.5} dot={false} />
                    <Area type="monotone" dataKey="Deletions" stroke="#ef4444" fill="url(#deletions)" strokeWidth={1.5} dot={false} />
                  </AreaChart>
                </ResponsiveContainer>
              ) : (
                <div className="flex flex-col items-center justify-center h-full opacity-20 animate-pulse">
                  <Activity className="w-10 h-10" />
                  <span className="text-[9px] italic mt-1">Loading...</span>
                </div>
              )}
            </div>
          </div>
        </div>

        {/* Storage Growth Bar Chart */}
        <div className="rounded-xl border border-slate-200 dark:border-slate-800 bg-card shadow-xs overflow-hidden">
          <div className="px-4 pt-3 pb-1.5">
            <div className="flex items-center gap-1.5">
              <BarChart3 className="w-3.5 h-3.5 text-primary" />
              <span className="text-xs font-bold tracking-tight">Storage Growth (30d)</span>
            </div>
          </div>
          <div className="min-h-[200px] px-3 pb-4">
            {storageHistory.length > 0 ? (() => {
              const days = Array.from(new Set(storageHistory.map((s) =>
                s.Timestamp.split('T')[0] || s.Timestamp.split(' ')[0]
              ))).sort()
              const buckets = Array.from(new Set(storageHistory.map((s) => s.Bucket)))
              const chartData = days.map((day) => {
                const row: Record<string, any> = { day: day.split('-').slice(1).join('/') }
                buckets.forEach((b) => {
                  const match = storageHistory.find((s) => s.Bucket === b && s.Timestamp.startsWith(day))
                  row[b] = match?.Size || 0
                })
                return row
              })
              return (
                <ResponsiveContainer width="100%" height={200}>
                  <BarChart data={chartData} margin={{ top: 5, right: 10, bottom: 0, left: 0 }}>
                    <CartesianGrid strokeDasharray="3 3" stroke="rgba(0,0,0,0.04)" />
                    <XAxis dataKey="day" tick={{ fontSize: 8 }} tickCount={10} />
                    <YAxis tick={{ fontSize: 8 }} tickFormatter={(v) => formatSize(v)} />
                    <Tooltip formatter={(v: any) => formatSize(v)} />
                    <Legend iconSize={8} wrapperStyle={{ fontSize: 9 }} />
                    {buckets.map((b, i) => (
                      <Bar key={b} dataKey={b} fill={CHART_COLORS[i % CHART_COLORS.length]} radius={[2, 2, 0, 0]} />
                    ))}
                  </BarChart>
                </ResponsiveContainer>
              )
            })() : (
              <div className="flex flex-col items-center justify-center h-full opacity-20 animate-pulse">
                <BarChart3 className="w-10 h-10" />
                <span className="text-[9px] italic mt-1">Loading...</span>
              </div>
            )}
          </div>
        </div>

        {/* Live System Activity Feed */}
        <div className="rounded-xl border border-slate-200 dark:border-slate-800 bg-card shadow-xs overflow-hidden flex flex-col">
          <div className="px-4 pt-3 pb-1.5 border-b flex items-center justify-between">
            <div className="flex items-center gap-1.5">
              <Activity className="w-3.5 h-3.5 text-emerald-500 animate-pulse" />
              <span className="text-xs font-bold tracking-tight">Live System Activity Feed</span>
            </div>
            <span className="text-[8px] font-bold uppercase tracking-widest text-muted-foreground px-2 py-0.5 rounded-full bg-slate-100 dark:bg-slate-800/80 border">
              Real-time
            </span>
          </div>
          <div className="max-h-72 overflow-y-auto divide-y font-mono text-[10px] bg-slate-950/20">
            {liveLogs.length > 0 ? (
              liveLogs.map((log, idx) => {
                const action = log.Action || log.action || ''
                const status = log.Status || log.status || ''
                const user = log.User || log.user || 'system'
                const resource = log.Resource || log.resource || '—'
                const timestamp = log.Timestamp || log.timestamp || ''
                
                const formattedTime = timestamp
                  ? new Date(timestamp).toLocaleTimeString()
                  : new Date().toLocaleTimeString()

                const isSuccess = status === 'success' || status === 'allowed'
                
                return (
                  <div key={idx} className="p-2.5 px-4 flex items-center justify-between hover:bg-muted/10 transition-colors">
                    <div className="flex items-center gap-3 min-w-0">
                      <span className="text-slate-500 shrink-0 select-none">{formattedTime}</span>
                      <Badge variant="outline" className={`text-[8px] font-bold px-1.5 h-4.5 uppercase tracking-wide shrink-0 ${
                        action.includes('Put')
                          ? 'border-emerald-500/20 text-emerald-500 bg-emerald-500/5'
                          : action.includes('Delete')
                            ? 'border-rose-500/20 text-rose-500 bg-rose-500/5'
                            : 'border-blue-500/20 text-blue-500 bg-blue-500/5'
                      }`}>
                        {action.replace('s3:', '')}
                      </Badge>
                      <span className="text-slate-700 dark:text-slate-300 font-bold shrink-0 truncate max-w-28" title={user}>
                        @{user}
                      </span>
                      <span className="text-muted-foreground truncate" title={resource}>
                        {resource}
                      </span>
                    </div>
                    <div className="flex items-center gap-2 shrink-0">
                      <span className={`text-[8px] font-extrabold uppercase px-1.5 py-0.5 rounded ${
                        isSuccess ? 'text-emerald-500 bg-emerald-500/10' : 'text-rose-500 bg-rose-500/10'
                      }`}>
                        {isSuccess ? 'Allowed' : 'Denied'}
                      </span>
                    </div>
                  </div>
                )
              })
            ) : (
              <div className="text-center py-8 text-muted-foreground italic">
                Waiting for incoming system activities...
              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  )
}
